export const LOAD_USERS = 'LOAD_USERS'
export const USERS_LOADED = 'USERS_LOADED'
export const USERS_FAILED = 'USERS_FAILED'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'
